# give the application a name
server:
  servlet:
    context-path: /wallet
spring:
  application:
    name: wallet
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:  
    hibernate:
      ddl-auto: update
  flyway:  
      enabled: false
